---
- hosts: localhost
  
  tasks:
    - name: Create A record in DNS zone {{ dns_zone }}
      community.aws.route53:
        state: present
        zone: "{{ dns_zone }}"
        record: "{{ dns_name }}"
        type: A
        ttl: 900
        value: "{{ ip_adress }}"
    
    - name: Check record for "{{ dns_name }}"
      community.aws.route53:
        state: get
        zone: "{{ dns_zone }}"
        record: "{{ dns_name }}"
        type: A
      register: wprecord
      
    - debug:
        msg: "{{ dns_name }}   IN  A      {{ wprecord.set.value }}"
    
    