---
- hosts: localhost
  tasks:
    - name: Create AWS instance {{ instance_name }} in {{ instance_region }}
      lightsail:
        state: present
        name: "{{ instance_name }}" 
        region: "{{ instance_region }}"
        zone: "{{ instance_zone }}"
        blueprint_id: "{{ instance_blueprint }}"
        bundle_id: "{{ instance_bundle }}"
        key_pair_name: "{{ key_name }}"
        user_data: "sudo apt update && sudo apt install -y python"
        wait_timeout: 4000